/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

typedef volatile unsigned int vuint32_t;

#include <stdint.h>
#define RCC_BASE      0x40021000
#define GPIOA_BASE    0X40010800
#define RCC_APB2ENR  *(volatile uint32_t *)(RCC_BASE + 0X18)
#define GPIOA_CRH   *(volatile uint32_t *)(GPIOA_BASE + 0X04)
#define GPIOA_ODR   *(volatile uint32_t *)(GPIOA_BASE + 0x0C)
#define GPIOA_CRL   *(volatile uint32_t *)(GPIOA_BASE + 0x00)

// bit fields
#define RCC_TOPAEN   (1<<2)
#define GPIO13       (1UL<<13)
#define EXTI_BASE     0X40010800
#define EXTI_IMR    *(volatile uint32_t *)(EXTI_BASE + 0x00)
#define EXTI_RTSR   *(volatile uint32_t *)(EXTI_BASE + 0x08)
#define EXTI_PR     *(volatile uint32_t *)(EXTI_BASE + 0x14)
#define AFIO_BASE       0X40010000
#define AFIO_EXTICR1    *(volatile uint32_t *)(AFIO_BASE + 0x08)
#define NVIC_EXTIE0    *(volatile uint32_t *)(0xE000E100)
void clock_init()
{
	RCC_APB2ENR |=RCC_TOPAEN;
}
void GPIO_init()
{
	GPIOA_CRH &=0XFF0FFFFF;
    GPIOA_CRH |=0X00200000;
    //pin A0 floating input (reset state)
    GPIOA_CRL |=(1<<2);
}
int main(void)
{
   //enable configuration to portA0
	AFIO_EXTICR1=0;
	//enable rising trigger
	EXTI_RTSR |=(1<<0);
	//enable EXTI line 0
	EXTI_IMR |=(1<<0);
	//enable NVIC IRQ <<>> EXTI0
	NVIC_EXTIE0 |=(1<<6);
	while(1);
}
void EXTI0_IRQHandler(void)
{
//IRQ IS HAPPENED >> GPIOA PIN0
 //toggle led pinA 13
	GPIOA_ODR ^=(1<<13);
	EXTI_PR |=(1<<0);
}
